name: Build and Release

on: workflow_dispatch

jobs:
  build_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
      - name: Build client package
        run: |
          cd packages/client
          npm install
          npm run build
      - name: npm install
        run: npm install
      - name: npm build
        run: npm run build
      - name: get-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1
      - name: check version
        run: |
          if [ -z "${{ steps.package-version.outputs.current-version }}" ]; then
            echo "No version found in package.json"
            exit 1
          fi
          echo "package.json version is ${{ steps.package-version.outputs.current-version }}"
          platform_version=$(grep '^export const PLATFORM_LIB_VERSION = ' packages/client/src/version.ts | cut -d'"' -f2)
          echo "PLATFORM_LIB_VERSION is $platform_version"
          if [ "${{ steps.package-version.outputs.current-version }}" != "$platform_version" ]; then
            echo "Version in package.json does not match PLATFORM_LIB_VERSION in packages/client/src/version.ts"
            exit 1
          fi
          echo "Version in package.json matches PLATFORM_LIB_VERSION"
      - name: release
        uses: actions/create-release@v1
        id: create_release
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          tag_name: 'v${{ steps.package-version.outputs.current-version}}'
          release_name: 'Release v${{ steps.package-version.outputs.current-version}}'
          draft: false
          prerelease: false
      - name: Upload release files
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/firebot-mage-platform-lib.js
          asset_name: firebot-mage-platform-lib-${{ steps.package-version.outputs.current-version}}.js
          asset_content_type: application/octet-stream
